# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-08 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_builder', '0010_auto_20160910_1037'),
        ('report_builder', '0004_auto_20170915_2046'),
    ]

    operations = [
    ]
